### ISSUE TITLE
Converging issue in 2D

### ISSUE THREAD

**Issue by JayaniJayasuriya** [reaxfire/gpyro#1]
Hi,

I have installed the latest version and tried out a two dimensional case that I'm working on for my research, but I ended up getting convergence error (attached). I have emailed my input files as a private email, I would be grateful if you could help me out with this. Thank you very much.  
![Capture](https://user-images.githubusercontent.com/40474636/97919133-2905ef80-1d0c-11eb-9e58-bfa38a2b01df.JPG)

**Comment by ghost** [comment]
This issue was moved to the google group: [here](https://groups.google.com/u/1/g/gpyro-working-group/c/nG2c7wGEuFs)

Ticket will be closed for now
